ALTER TABLE HOME ADD BattleZone3X int NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone3Z int NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone3LX tinyint NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone3LZ tinyint NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone4X int NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone4Z int NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone4LX tinyint NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone4LZ tinyint NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone5X int NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone5Z int NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone5LX tinyint NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone5LZ tinyint NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone6X int NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone6Z int NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone6LX tinyint NOT NULL DEFAULT (0)
ALTER TABLE HOME ADD BattleZone6LZ tinyint NOT NULL DEFAULT (0)

DELETE FROM START_POSITION WHERE ZoneID = 61
DELETE FROM START_POSITION WHERE ZoneID = 62
DELETE FROM START_POSITION WHERE ZoneID = 63
DELETE FROM START_POSITION WHERE ZoneID = 64
DELETE FROM START_POSITION WHERE ZoneID = 65
DELETE FROM START_POSITION WHERE ZoneID = 66
DELETE FROM START_POSITION WHERE ZoneID = 69

INSERT INTO START_POSITION VALUES (61,820,98,113,768,5,5,0,0,0,0);
INSERT INTO START_POSITION VALUES (62,63,159,960,884,5,5,0,0,0,0);
INSERT INTO START_POSITION VALUES (63,176,72,824,924,5,5,0,0,0,0);
INSERT INTO START_POSITION VALUES (64,76,729,244,945,5,5,0,0,0,0);
INSERT INTO START_POSITION VALUES (65,76,729,244,945,5,5,0,0,0,0);
INSERT INTO START_POSITION VALUES (66,76,729,244,945,5,5,0,0,0,0);
INSERT INTO START_POSITION VALUES (69,63,159,960,884,5,5,0,0,0,0);

UPDATE HOME SET FreeZoneX = 1380, FreeZoneZ = 1090, BattleZone2X = 61, BattleZone2Z = 158, BattleZone3X = (SELECT sKarusX FROM START_POSITION WHERE ZoneID = 63), BattleZone3Z = (SELECT sKarusZ FROM START_POSITION WHERE ZoneID = 63), BattleZone3LX = 5, BattleZone3LZ = 5, BattleZone4X = (SELECT sKarusX FROM START_POSITION WHERE ZoneID = 64), BattleZone4Z = (SELECT sKarusZ FROM START_POSITION WHERE ZoneID = 64), BattleZone4LX = 5, BattleZone4LZ = 5, BattleZone5X = (SELECT sKarusX FROM START_POSITION WHERE ZoneID = 65), BattleZone5Z = (SELECT sKarusZ FROM START_POSITION WHERE ZoneID = 65), BattleZone5LX = 5, BattleZone5LZ = 5, BattleZone6X = (SELECT sKarusX FROM START_POSITION WHERE ZoneID = 66), BattleZone6Z = (SELECT sKarusZ FROM START_POSITION WHERE ZoneID = 66), BattleZone6LX = 5, BattleZone6LZ = 5  WHERE Nation = 1
UPDATE HOME SET FreeZoneX = 630, FreeZoneZ = 920, BattleZone2X = 960, BattleZone2Z = 883, BattleZone3X = (SELECT sElmoradX FROM START_POSITION WHERE ZoneID = 63), BattleZone3Z = (SELECT sElmoradZ FROM START_POSITION WHERE ZoneID = 63), BattleZone3LX = 5, BattleZone3LZ = 5, BattleZone4X = (SELECT sElmoradX FROM START_POSITION WHERE ZoneID = 64), BattleZone4Z = (SELECT sElmoradZ FROM START_POSITION WHERE ZoneID = 64), BattleZone4LX = 5, BattleZone4LZ = 5, BattleZone5X = (SELECT sElmoradX FROM START_POSITION WHERE ZoneID = 65), BattleZone5Z = (SELECT sElmoradZ FROM START_POSITION WHERE ZoneID = 65), BattleZone5LX = 5, BattleZone5LZ = 5, BattleZone6X = (SELECT sElmoradX FROM START_POSITION WHERE ZoneID = 66), BattleZone6Z = (SELECT sElmoradZ FROM START_POSITION WHERE ZoneID = 66), BattleZone6LX = 5, BattleZone6LZ = 5  WHERE Nation = 2